// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: im-user.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户省份验证 输入输出参数
type AuthReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *AuthReq) Reset() {
	*x = AuthReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReq) ProtoMessage() {}

func (x *AuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReq.ProtoReflect.Descriptor instead.
func (*AuthReq) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{0}
}

func (x *AuthReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State int64 `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *AuthResp) Reset() {
	*x = AuthResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResp) ProtoMessage() {}

func (x *AuthResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResp.ProtoReflect.Descriptor instead.
func (*AuthResp) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResp) GetState() int64 {
	if x != nil {
		return x.State
	}
	return 0
}

var File_im_user_proto protoreflect.FileDescriptor

var file_im_user_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x69, 0x6d, 0x2d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x1f, 0x0a, 0x07, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x20, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x32, 0x38, 0x0a, 0x09, 0x49, 0x4d, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x50, 0x43, 0x12, 0x2b, 0x0a, 0x0e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52,
	0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_im_user_proto_rawDescOnce sync.Once
	file_im_user_proto_rawDescData = file_im_user_proto_rawDesc
)

func file_im_user_proto_rawDescGZIP() []byte {
	file_im_user_proto_rawDescOnce.Do(func() {
		file_im_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_im_user_proto_rawDescData)
	})
	return file_im_user_proto_rawDescData
}

var file_im_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_im_user_proto_goTypes = []interface{}{
	(*AuthReq)(nil),  // 0: pb.AuthReq
	(*AuthResp)(nil), // 1: pb.AuthResp
}
var file_im_user_proto_depIdxs = []int32{
	0, // 0: pb.IMUserRPC.Authentication:input_type -> pb.AuthReq
	1, // 1: pb.IMUserRPC.Authentication:output_type -> pb.AuthResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_im_user_proto_init() }
func file_im_user_proto_init() {
	if File_im_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_im_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_im_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_im_user_proto_goTypes,
		DependencyIndexes: file_im_user_proto_depIdxs,
		MessageInfos:      file_im_user_proto_msgTypes,
	}.Build()
	File_im_user_proto = out.File
	file_im_user_proto_rawDesc = nil
	file_im_user_proto_goTypes = nil
	file_im_user_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IMUserRPCClient is the client API for IMUserRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IMUserRPCClient interface {
	Authentication(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthResp, error)
}

type iMUserRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewIMUserRPCClient(cc grpc.ClientConnInterface) IMUserRPCClient {
	return &iMUserRPCClient{cc}
}

func (c *iMUserRPCClient) Authentication(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthResp, error) {
	out := new(AuthResp)
	err := c.cc.Invoke(ctx, "/pb.IMUserRPC/Authentication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IMUserRPCServer is the server API for IMUserRPC service.
type IMUserRPCServer interface {
	Authentication(context.Context, *AuthReq) (*AuthResp, error)
}

// UnimplementedIMUserRPCServer can be embedded to have forward compatible implementations.
type UnimplementedIMUserRPCServer struct {
}

func (*UnimplementedIMUserRPCServer) Authentication(context.Context, *AuthReq) (*AuthResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authentication not implemented")
}

func RegisterIMUserRPCServer(s *grpc.Server, srv IMUserRPCServer) {
	s.RegisterService(&_IMUserRPC_serviceDesc, srv)
}

func _IMUserRPC_Authentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMUserRPCServer).Authentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.IMUserRPC/Authentication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMUserRPCServer).Authentication(ctx, req.(*AuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _IMUserRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.IMUserRPC",
	HandlerType: (*IMUserRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authentication",
			Handler:    _IMUserRPC_Authentication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "im-user.proto",
}
